# Generated by Django 2.2.24 on 2021-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_mycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
