# Generated by Django 2.2.24 on 2021-06-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20210624_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='name',
        ),
    ]
