# Generated by Django 2.2.24 on 2021-06-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_auto_20210625_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prize',
            new_name='price',
        ),
    ]
